PROCESS BEFORE OUTPUT.
  MODULE status_0500.
  MODULE init_fields_0500.

PROCESS AFTER INPUT.
  MODULE exit_command AT EXIT-COMMAND.
  MODULE user_command_0500.

PROCESS ON VALUE-REQUEST.
  FIELD gv_variant MODULE f4_gv_variant.
